name: tests
on: pull_request

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bundle Install
        run: bundle install
        
      - name: Unit tests
        run: bundle exec fastlane tests
